production:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr'
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr'
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr'
    log_level: WARNING